# Colors Doric-Wind
[colors.normal]
black = '#d5e1d9'
red = '#990020'
green = '#006710'
yellow = '#706000'
blue = '#003370'
magenta = '#782050'
cyan = '#006070'
white = '#000f0f'
[colors.bright]
black = '#d5e1d9'
red = '#990020'
green = '#006710'
yellow = '#706000'
blue = '#003370'
magenta = '#782050'
cyan = '#006070'
white = '#000f0f'
[colors.cursor]
cursor = '#10600b'
text = '#e8f0e9'
[colors.primary]
background = '#e8f0e9'
foreground = '#000f0f'
[colors.selection]
background = '#94c2bf'
text = '#000f0f'
