# Colors Doric-Light
[colors.normal]
black = '#efeff2'
red = '#a01010'
green = '#106710'
yellow = '#60400f'
blue = '#103077'
magenta = '#700d50'
cyan = '#005355'
white = '#000000'
[colors.bright]
black = '#efeff2'
red = '#a01010'
green = '#106710'
yellow = '#60400f'
blue = '#103077'
magenta = '#700d50'
cyan = '#005355'
white = '#000000'
[colors.cursor]
cursor = '#2266bb'
text = '#ffffff'
[colors.primary]
background = '#ffffff'
foreground = '#000000'
[colors.selection]
background = '#a0bcd0'
text = '#000000'
