# Colors Doric-Obsidian
[colors.normal]
black = '#2f2f2f'
red = '#eca28f'
green = '#b9d0aa'
yellow = '#c0b080'
blue = '#9fbfe7'
magenta = '#e9acbf'
cyan = '#a0c0d0'
white = '#e7e7e7'
[colors.bright]
black = '#2f2f2f'
red = '#eca28f'
green = '#b9d0aa'
yellow = '#c0b080'
blue = '#9fbfe7'
magenta = '#e9acbf'
cyan = '#a0c0d0'
white = '#e7e7e7'
[colors.cursor]
cursor = '#eeddbb'
text = '#181818'
[colors.primary]
background = '#181818'
foreground = '#e7e7e7'
[colors.selection]
background = '#505050'
text = '#e7e7e7'
