# Colors Ef-Light
[colors.normal]
black = '#efefef'
red = '#d3303a'
green = '#217a3c'
yellow = '#a45f22'
blue = '#3740cf'
magenta = '#ba35af'
cyan = '#1f6fbf'
white = '#202020'
[colors.bright]
black = '#b3b3b3'
red = '#d51272'
green = '#008858'
yellow = '#b65050'
blue = '#065fff'
magenta = '#6052cf'
cyan = '#1f77bb'
white = '#68759f'
[colors.cursor]
cursor = '#0033cc'
text = '#ffffff'
[colors.primary]
background = '#ffffff'
foreground = '#202020'
[colors.selection]
background = '#bfefff'
text = '#202020'
